# Generated by Django 5.2.3 on 2025-07-01 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_vs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='imagem',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
