# Generated by Django 5.2.3 on 2025-07-02 04:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='capa',
            field=models.ImageField(blank=True, null=True, upload_to='capas_obras/'),
        ),
        migrations.CreateModel(
            name='Capitulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=120)),
                ('conteudo', models.TextField(max_length=20000)),
                ('ordem', models.PositiveIntegerField()),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('colecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='capitulos', to='obras_vs.colecao')),
            ],
        ),
    ]
