# Generated by Django 5.2.3 on 2025-07-21 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='publicado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='obra',
            name='rascunho',
            field=models.TextField(blank=True, default=''),
        ),
    ]
