# Generated by Django 5.2.3 on 2025-07-02 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0002_obra_capa_capitulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='obra',
            name='capa',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
