# Generated by Django 5.2.3 on 2025-07-04 16:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0003_alter_obra_capa'),
    ]

    operations = [
        migrations.AddField(
            model_name='colecao',
            name='data_criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='colecao',
            name='titulo',
            field=models.CharField(default='Obra sem título', max_length=200),
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True, default=''),
        ),
    ]
