# Generated by Django 5.2.3 on 2025-07-05 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0004_colecao_data_criacao_colecao_titulo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='paginas',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='obra',
            name='conteudo',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='obra',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
