# Generated by Django 5.2.3 on 2025-07-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0005_obra_paginas_alter_obra_conteudo_alter_obra_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colecao',
            name='data_criacao',
        ),
        migrations.RemoveField(
            model_name='colecao',
            name='titulo',
        ),
        migrations.AlterField(
            model_name='colecao',
            name='descricao',
            field=models.TextField(blank=True),
        ),
    ]
