# Generated by Django 5.2.3 on 2025-07-18 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('obras_vs', '0006_remove_colecao_data_criacao_remove_colecao_titulo_and_more'),
    ]

    operations = [
    ]
